### PR TITLE
Major upgrades

### PR DESCRIPTION
**Pull request by francislavoie**
- Updated every dependency
- Switched from Vue CLI to Vite (required moving HTML files etc)
- Filled out the README
- Eslint does not work as-is (bad config) but that can be left for later
- Fixed all existing type errors
- Added classic hero icons, higher res race icons and random-race variants
- Moved files around, deleted some demo files
- Added streamer's own battle tag at the top-left
- Added links to W3C website on usernames (ongoing match, match result, streamer's in top-left) opens in new tab with `target="_blank"`
- Reworked all screens for visual clarity and information density
- Refresh ongoing match every 30s while opened

image

image

image

image

### CODE REVIEW

**Review by marcoabreu — APPROVED** [review]

**Comment by marcoabreu** [comment]
What is the experience like for non 1v1/melee games?

**Comment by francislavoie** [comment]
Non-1v1 is still not supported yet (that's unchanged). I plan on doing another pass after this to add support for other game modes. It'll need new UI for when there's more than two players etc. Also need to consider what to do with "today's results" and how to combine both 1v1 and non-1v1 results.

**Review by gustav87 — APPROVED** [review]

**Comment by marcoabreu** [comment]
So will it handle non 1v1 gracefully or show broken results?

**Comment by francislavoie** [comment]
It just says "No 1v1 match currently in progress" if you're in a different mode. That's the same as it was before. When it fetches the ongoing match it checks the game mode and ignores it if it's not 1v1 for now.

**Comment by francislavoie** [comment]
For the record, I submitted the new version with this information:

```
This extension displays the streamer's current live match and daily stats for Warcraft III when played through the W3Champions community platform, i.e. https://w3champions.com/

Walkthrough:
- Add to any channel
- Open https://w3champions.com/matches and click on one of the first few usernames you see
- Copy the "battle tag" at the top of the page (e.g. SomeUsername#1234)
- Open the extension's config page, enter this battle tag there. This configures which user for which the extension will display live/daily stats.
- Open the overlay on the twitch stream, click the blue button on the left to open the panel
- See the live match data for the player you chose (and their opponent).
- Click the Today Results tab at the top to see their match history since the stream went live (probably empty unless doing the test some time after going live, but that's fine).
- Click on the username in the top-left, or the opponent's name on the Current Match tab to open the profile page for that user in a new tab (link with target="_blank")
- That's it!

Availability: I assume the above should be enough to review at any time without our involvement. It doesn't require a running game (can point to any user currently playing to see live stats) and can be added to any stream (you can use your own I assume).

Changelog: This version is effectively a major modernization from the prior version. The project is open source, this version's changes are here: https://github.com/w3champions/twitch-extension/pull/2
```

**Pull request merged**
